version: '3.8'

services:
  frontend:
    build: .
    environment:
      - NEXT_PUBLIC_API_URL=ws://localhost:4000
    ports:
      - "5000:5000"
    networks:
      - support-network

networks:
  support-network:
    external: true